INSERT INTO Game_List SET GameEName='RTG 777', GameName='RTG 777' , GameVendor=37 , TheirGameId=1179882 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='BAO NI 8', GameName='包你發' , GameVendor=37 , TheirGameId=1179912 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Lucky Rat', GameName='鼠來寶' , GameVendor=37 , TheirGameId=1179906 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Wu Zetian', GameName='武則天' , GameVendor=37 , TheirGameId=1179889 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Gemtopia', GameName='寶石天堂' , GameVendor=37 , TheirGameId=1179842 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Heavenly Treasure', GameName='天官賜寶' , GameVendor=37 , TheirGameId=1179803 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Super 6', GameName='超級 6' , GameVendor=37 , TheirGameId=1179819 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Three Kingdom Wars (San Guo Sheng Ba)', GameName='三國爭霸' , GameVendor=37 , TheirGameId=1179885 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='T-REX 2', GameName='暴龍 2' , GameVendor=37 , TheirGameId=1179897 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fucanglong', GameName='伏藏龍' , GameVendor=37 , TheirGameId=1179837 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Swindle All The Way', GameName='一路搶到底' , GameVendor=37 , TheirGameId=1179869 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='The Mariachi 5', GameName='開心鬼派對' , GameVendor=37 , TheirGameId=1179901 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fat Cat Café', GameName='肥貓咖啡' , GameVendor=37 , TheirGameId=1179904 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Pig Winner', GameName='豬滿冠' , GameVendor=37 , TheirGameId=1179893 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Dragon Orb', GameName='龍珠' , GameVendor=37 , TheirGameId=1179841 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Kung Fu Rooster', GameName='功夫雄雞' , GameVendor=37 , TheirGameId=1179847 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Storm Lords', GameName='王者風暴' , GameVendor=37 , TheirGameId=1179899 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Trigger Happy', GameName='西部喜雙逢' , GameVendor=37 , TheirGameId=1179895 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Secret Symbol', GameName='秘密符號' , GameVendor=37 , TheirGameId=1179838 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Cai Hong', GameName='彩虹' , GameVendor=37 , TheirGameId=1179879 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Panda\'s Gold', GameName='熊貓黃金' , GameVendor=37 , TheirGameId=1179876 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Snowmania', GameName='冰雪風暴' , GameVendor=37 , TheirGameId=1179828 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Sweet 16', GameName='甜蜜 16 歲' , GameVendor=37 , TheirGameId=1179830 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Popiñata', GameName='皮納塔狂歡' , GameVendor=37 , TheirGameId=1179839 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fortune Frog', GameName='幸運蛙' , GameVendor=37 , TheirGameId=1179907 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fire Dragon', GameName='火龍特務' , GameVendor=37 , TheirGameId=1179883 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Nova 7s', GameName='夢幻之星' , GameVendor=37 , TheirGameId=1179825 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Lucha Libre 2', GameName='墨西哥摔角2' , GameVendor=37 , TheirGameId=1179874 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Mermaid\'s Pearls', GameName='雪碧人魚失落之寶藏' , GameVendor=37 , TheirGameId=1179894 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Bubble Bubble 2', GameName='女巫溫妮 2' , GameVendor=37 , TheirGameId=1179848 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Football Fortunes', GameName='幸運足球' , GameVendor=37 , TheirGameId=1179898 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Cash Bandits 2', GameName='警匪追逐2' , GameVendor=37 , TheirGameId=1179846 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Scuba Fishing', GameName='漁民樂' , GameVendor=37 , TheirGameId=1179888 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Stardust', GameName='星塵' , GameVendor=37 , TheirGameId=1179884 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Naughty Or Nice III', GameName='頑皮女孩或漂亮女孩 III' , GameVendor=37 , TheirGameId=1179890 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='I, Zombie', GameName='僵屍' , GameVendor=37 , TheirGameId=1179880 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Shanghai Lights', GameName='霓虹上海' , GameVendor=37 , TheirGameId=1179870 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Gods of Nature (Tian Di Yuan Su)', GameName='天地元素' , GameVendor=37 , TheirGameId=1179886, GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fu Chi', GameName='福氣' , GameVendor=37 , TheirGameId=1179868 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fantasy Mission Force', GameName='迷你特攻隊' , GameVendor=37 , TheirGameId=1179871 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Ancient Gods (Yuan Gu Sheng Shou)', GameName='遠古神獸' , GameVendor=37 , TheirGameId=1179887 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Football Frenzy', GameName='足球狂熱' , GameVendor=37 , TheirGameId=1179802 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Eternal Love', GameName='永恆的愛' , GameVendor=37 , TheirGameId=1179816 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Panda Magic', GameName='魔幻貓熊' , GameVendor=37 , TheirGameId=1179822 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Texan Tycoon', GameName='德州大亨' , GameVendor=37 , TheirGameId=1179709 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Enchanted Garden II', GameName='夢幻花園 II' , GameVendor=37 , TheirGameId=1179821 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Bubble Bubble', GameName='女巫溫妮' , GameVendor=37 , TheirGameId=1179813 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Loch Ness Loot', GameName='尼斯湖水怪' , GameVendor=37 , TheirGameId=1179773 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Coyote Cash', GameName='惡棍郊狼' , GameVendor=37 , TheirGameId=1179692 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Enchanted Garden', GameName='夢幻花園' , GameVendor=37 , TheirGameId=1179672 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Samba Sunset', GameName='桑巴日落' , GameVendor=37 , TheirGameId=1179823 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Secret Jungle', GameName='秘密叢林' , GameVendor=37 , TheirGameId=1179877 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Asgard', GameName='阿薩神域' , GameVendor=37 , TheirGameId=1179840 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Lucky 6', GameName='幸運 6' , GameVendor=37 , TheirGameId=1179811 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Witch\'s Brew', GameName='女巫的秘方' , GameVendor=37 , TheirGameId=1179826 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Eagle Shadow Fist', GameName='北派功夫' , GameVendor=37 , TheirGameId=1179872 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='The Naughty List', GameName='聖誕風騷女' , GameVendor=37 , TheirGameId=1179805 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='High Fashion', GameName='模特夢' , GameVendor=37 , TheirGameId=1179798 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Purrfect Pets', GameName='完美寵物' , GameVendor=37 , TheirGameId=1179843 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Ritchie Valens™ La Bamba', GameName='里奇·瓦倫斯' , GameVendor=37 , TheirGameId=1179873 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Achilles', GameName='古希臘英雄' , GameVendor=37 , TheirGameId=1179681 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Goldbeard', GameName='金鬍子' , GameVendor=37, TheirGameId=1179653 , GameType = 2 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Aladdin\'s Wishes', GameName='阿拉丁的願"望"' , GameVendor=37 , TheirGameId=1179674 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Cleopatras Gold', GameName='埃及豔后' , GameVendor=37 , TheirGameId=1179651 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Ghost Ship', GameName='幽靈船' , GameVendor=37 , TheirGameId=1179790 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Cash Bandits', GameName='警匪追逐' , GameVendor=37 , TheirGameId=1179809 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Builder Beaver', GameName='海狸伐木先生' , GameVendor=37 , TheirGameId=1179771 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Pay Dirt', GameName='金礦探索' , GameVendor=37 , TheirGameId=1179698 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Crystal Waters', GameName='深海遨游' , GameVendor=37 , TheirGameId=1179675 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Naughty Or Nice', GameName='淘氣或乖乖' , GameVendor=37 , TheirGameId=1179714 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='T Rex', GameName='暴龍' , GameVendor=37 , TheirGameId=1179700 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Henhouse', GameName='農村人家' , GameVendor=37 , TheirGameId=1179769 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Megaquarium', GameName='財富水族箱' , GameVendor=37 , TheirGameId=1179836 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Lucky 8', GameName='幸運 8' , GameVendor=37 , TheirGameId=1179770 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Triple Twister', GameName='龍捲風' , GameVendor=37 , TheirGameId=1179710 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Regal Riches', GameName='貴族富豪' , GameVendor=37 , TheirGameId=1179796 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Caesar\'s Empire', GameName='凱撒帝國' , GameVendor=37 , TheirGameId=1179654 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='The Three Stooges II', GameName='The Three Stooges II' , GameVendor=37 , TheirGameId=1179858 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='God of Wealth', GameName='財神到' , GameVendor=37 , TheirGameId=1179817 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Zhanshi', GameName='古代戰士' , GameVendor=37 , TheirGameId=1179820 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Count Spectacular', GameName='吸血伯爵' , GameVendor=37 , TheirGameId=1179727 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Double Ya Luck!', GameName='三喜臨門' , GameVendor=37 , TheirGameId=1179862 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Hillbillies', GameName='鄉下佬' , GameVendor=37 , TheirGameId=1179664 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Mermaid Queen', GameName='人魚女王' , GameVendor=37 , TheirGameId=1179663 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Ninja Star', GameName='忍者星' , GameVendor=37 , TheirGameId=1179779 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Ocean Oddities', GameName='海洋生物' , GameVendor=37 , TheirGameId=1179795 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Penguin Power', GameName='企鵝力量' , GameVendor=37 , TheirGameId=1179685 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Return of the Rudolph', GameName='馴鹿魯道夫' , GameVendor=37 , TheirGameId=1179732 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Rudolphs Revenge', GameName='魯道夫的復仇' , GameVendor=37 , TheirGameId=1179693 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Santastic', GameName='奇妙聖誕' , GameVendor=37 , TheirGameId=1179861 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Small Fortune', GameName='郊外野餐' , GameVendor=37 , TheirGameId=1179797 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='The Nice List', GameName='繽紛聖誕' , GameVendor=37 , TheirGameId=1179814 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='The Three Stooges® Brideless Groom', GameName='The Three Stooges Brideless Groom' , GameVendor=37 , TheirGameId=1179807 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Voodoo Magic', GameName='伏都巫術' , GameVendor=37 , TheirGameId=1179804 , GameType = 2 ;
INSERT INTO Game_List SET GameEName='Banana Jones', GameName='奪寶小靈猴' , GameVendor=37 , TheirGameId=2228225, GameType = 2 ;
INSERT INTO Game_List SET GameEName='Fish Catch', GameName='捕魚',Note='Fishing' , GameVendor=37 , TheirGameId=2162689 , GameType = 2 ;